### ISSUE TITLE
Blender import places some objects at center of map

### ISSUE THREAD

**Issue by callumhutchy** [Jonathan-Greve/GuildWarsMapBrowser#17]
![Screenshot_36](https://github.com/Jonathan-Greve/GuildWarsMapBrowser/assets/4421540/6030fff3-6ae1-41a3-a5ae-391f6eccf0e5)

In the Map Browser all the scene objects appear to be in the correct place, but when exporting the map and importing with the blender addon, some of the scene objects are positioned at the center of the map. They also appear to be duplicates, as there is copies in the correct places.

![Screenshot_37](https://github.com/Jonathan-Greve/GuildWarsMapBrowser/assets/4421540/c6c8066c-67ea-4238-929f-04a34b1d32c4)

Version of blender used is 4.0 and .dat is latest version as of 3rd June 2024.

**Comment by Jonathan-Greve** [comment]
Yes the import does two things.

1) Import all the models. By default blender shows all objects at the center.
2) Use links to those models rather than creating a new copy for each location it is placed at in the map. This saves memory since each model only has to be stored in memory/disk one time and then it can be placed multiple by just transforming it.

So hopefully the problem is just that you haven't hidden the models. You can hide them by pressing the eye icon here: 
![image](https://github.com/Jonathan-Greve/GuildWarsMapBrowser/assets/16852003/0122284f-75bb-469a-a36d-ecc2e68e96b7)

If that doesn't fix it please let me know :)

**Comment by callumhutchy** [comment]
Yeah that fixed it. Sorry for wasting time.
