### ISSUE TITLE
Option to export the entire map + models

### ISSUE THREAD

**Issue by aphexnl** [Jonathan-Greve/GuildWarsMapBrowser#3]
As mentioned on Reddit, I would love to have the option to export the entire map including every model. It's pretty much the only thing I can currently think of that is missing for me personally right now.

Either exporting the map + all models separately with a way to import them into a 3d editor at their proper locations or everything put together in one big mesh would be awesome.

Loving the tool so far!

**Comment by Jonathan-Greve** [comment]
That's a great idea. I've added it to the v5.0 release milestone. This should be on the easier side since it's something I have full control over - unlike the GW files contained in the .dat which are a pain to reverse. I'll most likely write an import script for Blender and hopefully I can get all the models imported separately and in the right locations with proper materials/shaders.

Thanks for creating the issue.

Reddit post referenced: [Introducing GuildWarsMapBrowser: A 3D Offline Exploration Tool for Guild Wars 1!](https://www.reddit.com/r/Guildwars2/comments/131a71s/introducing_guildwarsmapbrowser_a_3d_offline/)

**Comment by aphexnl** [comment]
That sounds really good! Looking forward to it!

**Comment by Jonathan-Greve** [comment]
Implemented in release v5.0.

**Comment by Jonathan-Greve** [comment]
Implemented in release v5.0.
